name: demo_clase_14
description: >
  App de demostración en vivo para la Clase 14 de Desarrollo de Aplicaciones
  Móviles (Flutter/Dart) — de InheritedWidget a Provider: introducción a la
  gestión de estado compartido.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
